quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.sql-load-script=import.sql
quarkus.datasource.username=quarkus
quarkus.datasource.password=quarkus
quarkus.datasource.jdbc.url=jdbc:postgresql://books-database:5432/books
quarkus.datasource.db-kind=postgresql

quarkus.http.cors=true
quarkus.kubernetes-client.trust-certs=true
quarkus.openshift.route.expose=true

quarkus.oidc.auth-server-url=https://kc.apps.cluster-hgzmt.hgzmt.sandbox1467.opentlc.com/realms/quarkus
quarkus.oidc.client-id=backend-service 
quarkus.oidc.credentials.secret=secret
quarkus.oidc.tls.verification=none

